### ISSUE TITLE
initializing a custom canvas with useWorker more than once throws

### ISSUE THREAD

**Issue by catdad** [catdad/canvas-confetti#106]
```
DOMException: Failed to set the 'width' property on 'HTMLCanvasElement': Cannot resize canvas after call to transferControlToOffscreen().
    at setCanvasRectSize (http://127.0.0.1:52161/src/confetti.js:233:18)
    at HTMLCanvasElement.fire [as confetti] (http://127.0.0.1:52161/src/confetti.js:457:9)
    at eval (eval at button.onclick (http://127.0.0.1:52161/index.html:199:11), <anonymous>:7:8)
    at HTMLButtonElement.button.onclick (http://127.0.0.1:52161/index.html:635:11)
```

**Comment by catdad** [comment]
Published in 1.1.2
