### ISSUE TITLE
Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by RJFares** [catdad/canvas-confetti#153]
Confetti is working fine when I do not specify a custom canvas, but when I do I receive an error.

A quick HTML snippet:

```
<canvas id="canvas"
></canvas>

<script>
    window.addEventListener('DOMContentLoaded', () => {
        window.confetti(document.getElementById('canvas'),{
            angle: randomInRange(55, 125),
            spread: randomInRange(50, 70),
            particleCount: randomInRange(50, 100),
            origin: { y: 0.6 }
        });
    });
</script>
```

Result:

```
app.js:35793 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': HTMLCanvasElement object could not be cloned.
    at execute (http://127.0.0.1:8000/js/app.js:35793:16)
    at http://127.0.0.1:8000/js/app.js:35823:11
    at new Promise (<anonymous>)
    at promise (http://127.0.0.1:8000/js/app.js:35738:14)
    at Worker.fireWorker [as fire] (http://127.0.0.1:8000/js/app.js:35808:16)
    at fire (http://127.0.0.1:8000/js/app.js:36276:23)

```

Any idea about the issue?

**Comment by catdad** [comment]
That is not the correct way to provide a custom canvas (you are essentially passing in invalid options). Please refer to the documentation for [`confetti.create`](https://github.com/catdad/canvas-confetti#confetticreatecanvas-globaloptions--function).
